/*Use an immediate assertion to test the behavior of the adder for 10 random stimuli generated by TB. */

module adder(
  input      [3:0] a,b,
  output reg [4:0] s
);
  
  
  always@(*)
    begin
      s = a + b;
    end
 
  
endmodule

////////////////////////////////////////////////////////////////////////////////////////////////////
module tb;
  
  reg [3:0] a, b;
  wire [4:0] s;
  
  adder dut (a, b, s);
  
  initial begin
    for(int i = 0; i < 10; i++) begin
      a = $urandom;
      b = $urandom;
      #10;
      assert(s == a+b) $info("Success at %0t",$time); 
      else $error("Failure at %0t",$time);
    end   
  end
  
/*  always@(*)begin
    assert(s == a+b) $info("Success at %0t",$time); else $error("Failure at %0t",$time);
  end */
  
   initial begin
    $dumpfile("dump.vcd"); 
    $dumpvars;
    $assertvacuousoff(0);
    #110;
    $finish();
  end
  
  
endmodule
